config/routes.rb
Rails.application.routes.draw do
  resources :entradas

  root 'entradas#index'

end

app/models/entrada.rb
class Entrada < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entradas_controller.rb
class EntradasController < ApplicationController
  before_action :set_entrada, only: [:show, :edit, :update, :destroy]

  # GET /entradas
  # GET /entradas.json
  def index
    @entradas = Entrada.all
  end

  # GET /entradas/1
  # GET /entradas/1.json
  def show
  end

  # GET /entradas/new
  def new
    @entrada = Entrada.new
  end

  # GET /entradas/1/edit
  def edit
  end

  # POST /entradas
  # POST /entradas.json
  def create
    @entrada = Entrada.new(entrada_params)

    respond_to do |format|
      if @entrada.save
        format.html { redirect_to @entrada, notice: 'Entrada was successfully created.' }
        format.json { render :show, status: :created, location: @entrada }
        format.js
      else
        format.html { render :new }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entradas/1
  # PATCH/PUT /entradas/1.json
  def update
    respond_to do |format|
      if @entrada.update(entrada_params)
        format.html { redirect_to @entrada, notice: 'Entrada was successfully updated.' }
        format.json { render :show, status: :ok, location: @entrada }
      else
        format.html { render :edit }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entradas/1
  # DELETE /entradas/1.json
  def destroy
    @entrada.destroy
    respond_to do |format|
      format.html { redirect_to entradas_url, notice: 'Entrada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrada
      @entrada = Entrada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrada_params
      params.require(:entrada).permit(:titulo, :contenido)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/views/entradas/_entrada.html.erb
<tr>
    <td><%= @entrada.titulo %></td>
    <td><%= @entrada.contenido %></td>
    <td><%= link_to 'Show', @entrada %></td>
    <td><%= link_to 'Edit', edit_entrada_path(@entrada) %></td>
    <td><%= link_to 'Destroy', @entrada, method: :delete, data: { confirm: 'Are you sure?' }%></td>
</tr>

app/views/entradas/_form.html.erb
<%= form_for(@entrada, remote: true, role: "form") do |f| %>
  <% if @entrada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entrada.errors.count, "error") %> prohibited this entrada from being saved:</h2>

      <ul>
      <% @entrada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entradas/create.js.erb
$('#new_entrada').remove();
$('#nuevo').show();
$('tbody').append('<%= j render(@entrada)%>');

app/views/entradas/edit.html.erb
<h1>Editing Entrada</h1>

<%= render 'form' %>

<%= link_to 'Show', @entrada %> |
<%= link_to 'Back', entradas_path %>

app/views/entradas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entradas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entradas.each do |entrada| %>
      <tr>
        <td><%= entrada.titulo %></td>
        <td><%= entrada.contenido %></td>
        <td><%= link_to 'Show', entrada, class: 'btn btn-primary btn-xs'%></td>
        <td><%= link_to 'Edit', edit_entrada_path(entrada), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', entrada, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_entrada_path, id: 'nuevo',  remote: true, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> Nueva Entrada
<% end %>

app/views/entradas/new.html.erb
<h1>New Entrada</h1>

<%= render 'form' %>

<%= link_to 'Back', entradas_path %>

app/views/entradas/new.js.erb
$('#nuevo').hide().after('<%= j render("form") %>');

app/views/entradas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @entrada.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @entrada.contenido %>
</p>

<%= link_to 'Edit', edit_entrada_path(@entrada) %> |
<%= link_to 'Back', entradas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Asincrono</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-3">
          <h3>Mi primer app con AJAX</h3>
        </div>
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>

</body>
</html>